spring:
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  zipkin:
    base-url: http://zipkin-service.gulimall:9411/
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.3:8848
    sentinel:
      transport:
        dashboard: 192.168.50.3:8333
        port: 8719
    alicloud:
      access-key:
      secret-key:
      oss:
        bucket: slienceme
        endpoint:
        domain:
  application:
    name: gulimall-third-party
server:
  port: 30000

sms:
  host:
  path:
  appcode:
  sms-sign-id:
  template-id:

management:
  endpoints:
    web:
      exposure:
        include: '*'

alibaba:
  cloud:
    access-key:
    secret-key:
    oss:
      bucket: slienceme
      endpoint: oss-cn-beijing.aliyuncs.com
